name: "i love yotsuba"
description: "my own journal and domestic violence"
author:
  name: Rizal M.S
  email: sol.rizal@gmail.com
  github: gegenokitaro
  twitter: rizal_hokage
  facebook: hokage.rizal

url: "gegenokitaro.github.io"

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments

gems: [jekyll-paginate]
