name: "s-thing"
description: "something about s-thing"

url: "gegenokitaro.github.io"

paginate: 10

markdown: kramdown
kramdown:
        use_coderay: true
        coderay:
                coderay_line_numbers: table
                coderay_css: class
permalink: pretty
pygments: true
